### ISSUE TITLE
Missing API `sdrad_get_stack_offset`

### ISSUE THREAD

**Issue by jialunzhang-psu** [EricssonResearch/secure-rewind-and-discard#1]
When compiling the following code

```rust
#![feature(allocator_api)]
use sdradrustffi::*;
use std::os::raw::c_void;
sandbox!(
    fn f(a: &[i32]) {}
);

fn main() {
    f(&[3]);
}
```

The linker complains about it referring a missing function as follows
```
sdradrustffi/src/lib.rs:89: undefined reference to `sdrad_get_stack_offset'
```

However, this function doesn't exist in the `sdrad` library.  How should I solve this?

**Comment by jialunzhang-psu** [comment]
Wrong repo.

**Comment by gulmezmerve** [comment]
Hi; 
Thank for reaching out! I am planning to work out!
