### ISSUE TITLE
`LD_PRELOAD not working with `__data_start`

### ISSUE THREAD

**Issue by jialunzhang-psu** [EricssonResearch/secure-rewind-and-discard#2]
At `sdrad.h:35`, the predefined symbol `__data_start` is referred. Then it turns out to be an undefined symbol in `libsdrad.so`, reflected in the result of `nm -g libsdrad.so`.

It brings a problem when I use `libsdrad.so` in the `LD_PRELOAD` way. When running something like
```
LD_PRELOAD=/usr/lib/libsdrad.so ./exe
```
the linker complains that 
```
symbol lookup error: /usr/lib/libsdrad.so: undefined symbol: __data_start
```

Any insight to fix this?

**Comment by gulmezmerve** [comment]
Thanks for reaching out @jialunzhang-psu! Could you let me know which platform are you trying out? 

`__data_start` is coming from linker scripts.

**Comment by jialunzhang-psu** [comment]
Platform Info
- 22.04.1-Ubuntu
- Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz

The symbol missing only happens with `LD_PRELOAD`, it works fine when I do it the `LD_LIBRARY_PATH` way.

To make it clearer: I wrote a toy shared library that prints `__data_start`, and it works fine if I link it dynamically in the `LD_LIBRARY_PATH` way. But the missing symbol is reported when I run it with `LD_PRELOAD`. In the `libsdrad.so` case, I need to run it in the `LD_PRELOAD` way, which also causes an the same error.

**Comment by gulmezmerve** [comment]
I pushed an example script of how you can use sdrad library here https://github.com/EricssonResearch/secure-rewind-and-discard/blob/main/examples/example.sh
I tested it on the Ubuntu 22.04.4 LTS.
If you provide your shared library, I can try it out and see what is going on there.
